find_trending_companies:
  description: >
    通过搜索最新新闻，找出{sector}领域新闻中最热门的公司。找出你之前没有发现过的新公司。
  expected_output: >
    {sector}领域的热门公司列表
  agent: trending_company_finder
  output_file: output/trending_companies.json

research_trending_companies:
  description: >
    根据热门公司列表，通过在线搜索为每个公司提供详细的分析报告
  expected_output: >
    包含每个公司详细分析的报告
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report.json

pick_best_company:
  description: >
    分析研究结果并选择最佳投资公司。
    向用户发送包含决策和一句话理由的推送通知。
    然后提供一份详细报告，说明为什么选择这家公司，以及哪些公司未被选中。
  expected_output: >
    所选公司及选择原因；未被选中的公司及原因。
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
